# Sales Records Analysis 
### Author: Maritza Ruiz 
### Exercise 2.E Using functions for analyzing data 

This notebook analyzes a small sales dataset using Python functions. Each function takes the full dataset as its first argument.

In [8]:
sales_data = [
    ('Laptop', 'East', 1200.00),
    ('Phone', 'West', 850.00),
    ('Tablet', 'East', 400.00),
    ('Monitor', 'South', 650.00),
    ('Keyboard', 'West', 75.00),
    ('Laptop', 'South', 1150.00),
    ('Phone', 'East', 900.00),
    ('Tablet', 'West', 425.00),
    ('Monitor', 'East', 680.00),
    ('Keyboard', 'South', 80.00),
    ('Laptop', 'West', 1300.00),
]

## Lab 1. Total sales by region

In [3]:
def region_total(data, region):
    return sum(amt for _, r, amt in data if r == region)

In [4]:
print(region_total(sales_data, 'East')) 
print(region_total(sales_data, 'West')) 
print(region_total(sales_data, 'South'))

3180.0
2650.0
1880.0


## Lab 2. Count of sales by region

In [5]:
def region_count(data, region):
    return sum(1 for _, r, amt in data if r == region)

In [6]:
print(region_count(sales_data, 'East')) 
print(region_count(sales_data, 'West')) 
print(region_count(sales_data, 'South'))

4
4
3


## Lab 3. Average sale amount by region

In [7]:
def region_average(data, region):
    total = region_total(data, region)
    count = region_count(data, region)
    if count == 0:
        return count
    else:
        region_average = total / count
        return region_average

In [9]:
print(region_average(sales_data, 'East')) 
print(region_average(sales_data, 'West')) 
print(region_average(sales_data, 'South'))
print(region_average(sales_data, 'North'))

795.0
662.5
626.6666666666666
0


## Lab 4. Filter by sale amount

In [9]:
def sales_above(data, threshold):
    sale_amount = []
    for record in data:
        if  record[2] > threshold:
            sale_amount.append(record)
  
    return sale_amount


In [10]:
results = sales_above(sales_data, 500)

for record in results:
    print(record)


('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)


## Lab 5. Top and bottom sale


In [13]:
def top_sale(data):
    return max(data, key=lambda s:s[2])
print(top_sale(sales_data))
def bottom_sale(data):
    return min(data, key=lambda s:s[2])
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


Top sale was Laptop in West region for $1,300.00.
Bottom sale was Keyboard in West region for $75.00.

## Lab 6. Apply a discount


In [ ]:
def apply_discount(data, discount_pct):
       return list(
            map(
                lambda s: (s[0], s[1], s[2] * (1 - discount_pct)),
                data
              )
       )


In [18]:
for record in sales_data[:3]:
    print(record)

discounted = apply_discount(sales_data, 0.15)
for record in discounted[:3]:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique regions

In [19]:
def unique_regions(data):
    return sorted(set(record[1] for record in data))

In [21]:
print(unique_regions(sales_data))

['East', 'South', 'West']


This is similar to DISTINCT in SQL, which could be useful to know of product names being sold and being able to sort them in alphabetical order. 

## Lab 8. Region summary

In [ ]:
def region_summary(data, region):